"""empty message

Revision ID: 81d6bf5bf404
Revises: 
Create Date: 2024-02-13 01:21:24.528692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d6bf5bf404'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('number_batch', sa.Integer(), nullable=True),
    sa.Column('date_batch', sa.Date(), nullable=True),
    sa.Column('nomenclature', sa.Text(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('index', sa.String(), nullable=True),
    sa.Column('date_begin', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_batch'),
    sa.UniqueConstraint('number_batch')
    )
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_code', sa.String(), nullable=True),
    sa.Column('number_batch_id', sa.Integer(), nullable=True),
    sa.Column('is_aggregated', sa.Boolean(), nullable=True),
    sa.Column('aggregated_at', sa.DateTime(), nullable=True),
    sa.Column('date_product', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['number_batch_id'], ['task.number_batch'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_code')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
