# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/aggregate.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import product_pb2 as protos_dot_product__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/aggregate.proto\x12\taggregate\x1a\x14protos/product.proto\">\n\x19ProductToAggregateRequest\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"3\n\x1aProductToAggregateResponse\x12\x15\n\ris_aggregated\x18\x01 \x01(\x08\x32u\n\x12\x41ggregationService\x12_\n\x10\x41ggregateProduct\x12$.aggregate.ProductToAggregateRequest\x1a%.aggregate.ProductToAggregateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.aggregate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCTTOAGGREGATEREQUEST']._serialized_start=59
  _globals['_PRODUCTTOAGGREGATEREQUEST']._serialized_end=121
  _globals['_PRODUCTTOAGGREGATERESPONSE']._serialized_start=123
  _globals['_PRODUCTTOAGGREGATERESPONSE']._serialized_end=174
  _globals['_AGGREGATIONSERVICE']._serialized_start=176
  _globals['_AGGREGATIONSERVICE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
