# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos import product_pb2 as protos_dot_product__pb2


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProducts = channel.unary_unary(
                '/product.ProductService/CreateProducts',
                request_serializer=protos_dot_product__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                )
        self.GetProductsList = channel.unary_unary(
                '/product.ProductService/GetProductsList',
                request_serializer=protos_dot_product__pb2.GetProductsListRequest.SerializeToString,
                response_deserializer=protos_dot_product__pb2.GetProductsListResponse.FromString,
                )
        self.AggregateProduct = channel.unary_unary(
                '/product.ProductService/AggregateProduct',
                request_serializer=protos_dot_product__pb2.AggregateRequest.SerializeToString,
                response_deserializer=protos_dot_product__pb2.AggregateResponse.FromString,
                )


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AggregateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProducts,
                    request_deserializer=protos_dot_product__pb2.CreateProductRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'GetProductsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductsList,
                    request_deserializer=protos_dot_product__pb2.GetProductsListRequest.FromString,
                    response_serializer=protos_dot_product__pb2.GetProductsListResponse.SerializeToString,
            ),
            'AggregateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.AggregateProduct,
                    request_deserializer=protos_dot_product__pb2.AggregateRequest.FromString,
                    response_serializer=protos_dot_product__pb2.AggregateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/CreateProducts',
            protos_dot_product__pb2.CreateProductRequest.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProductsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/GetProductsList',
            protos_dot_product__pb2.GetProductsListRequest.SerializeToString,
            protos_dot_product__pb2.GetProductsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AggregateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/AggregateProduct',
            protos_dot_product__pb2.AggregateRequest.SerializeToString,
            protos_dot_product__pb2.AggregateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
